<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np

|Term   |Brief Description|
|:--:|:----:|
|Subsetting|Selecting|
|Indexing|Picking out a specific element from data|
|Slicing|Picking out a group of elements from data|
|Masking|Hiding a group of elements from data|

In [41]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
new_np_array_2d = np_array_2d[:,0].astype(float)
new_new_np_array = (new_np_array_2d%2)
my_mask = new_new_np_array == 1
np_array_2d[my_mask][:,1]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [48]:
data = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])



below50 = (data<50)
above50 = (data>50)
is50 = (data==50)
data[below50] = -1
data[above50] = +1
data [is50] = 0

print(data)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
