<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Fundamentals (Good)</span></div>

# What to expect in this chapter

In [11]:
import numpy as np

# 1 There is more to if

In [5]:
name = 'Batman'

if name == 'Batman':
    print('Hello Batman')
elif name == 'Robin':
    print('Hello Sidekick')
elif name == 'Chee Onn':
    print('Hello Chee Onn!')
else:
    print('Hello World!')

Hello Batman


# 2 Asking questions

In [6]:
fruits = ['apple','banana', 'pineapple', 'jackfruit']
vegetables= ['celery','potato','brocoli','kale']

In [7]:
('kiwi' in fruits) and ('kale' in vegetables)

False

In [8]:
'kale' not in vegetables

False

In [9]:
'app' in 'apple'

True

In [10]:
'apple' > 'organges'

False

In [11]:
'a' > 'b'

False

## 2.1 Asking Math questions

In [2]:
x=10

In [3]:
x > 5 and x < 15

True

In [4]:
(x > 5) and (x < 15)

True

In [5]:
5 < x < 15

True

# 3 Python stores information in different formats or types

In [12]:
x = int(1.234)
print(f"{x=}", type(x), )

x=1 <class 'int'>


In [13]:
x = str(1.234)
print(f"{x=}", type(x), )

x='1.234' <class 'str'>


In [14]:
x = float(1.234)
print(f"{x=}", type(x), )

x=1.234 <class 'float'>


In [15]:
x = complex(1.234)
print(f"{x=}", type(x), )

x=(1.234+0j) <class 'complex'>


In [18]:
np.float16([10])

array([10.], dtype=float16)

In [19]:
np.float32([10])

array([10.], dtype=float32)

In [20]:
np.float64([10])

array([10.])

# 4 Never compare floats directly

## 4.1 The Problem

In [21]:
a = 0.1
a3 = .3
a*3

0.30000000000000004

In [22]:
f'{0.3:.27f}'

'0.299999999999999988897769754'

## 4.2 A solution

In [8]:
a = 0.1
a3 = .3
a*3

0.30000000000000004

In [9]:
abs(a3 - 3*a) < 1E-10

True

In [13]:
np.isclose(a3,3*a)

np.True_

# 5 Combining English and variables

In [ ]:
name = "Batman"
print(f"Hello {name}!")

Hello Batman!


In [3]:
name = "Batman"
print(f"Hello {name.upper()}!")

Hello BATMAN!


In [4]:
x = 10
print(f"The value of {x} squared is {x**2}!")

The value of 10 squared is 100!


In [6]:
text = 'Bruce Wayne is Batman.'
print(f'{text}')

Bruce Wayne is Batman.


In [ ]:
print(f'{text:>30}')      # A block of 30 characters; Aligned Right

        Bruce Wayne is Batman.


In [ ]:
print(f'{text:^30}')      # A block of 30 characters; Aligned Centre

    Bruce Wayne is Batman.    


In [9]:
print(f'{text:<30}')      # A block of 30 characters; Aligned Left

Bruce Wayne is Batman.        


In [12]:
print(f'The cube of pi to 6 decimal places is {np.pi**3:.6f}') #Using the formatting to limit the decimal numbers of pi

The cube of pi to 6 decimal places is 31.006277


In [13]:
print(f'The cube of pi to 6 decimal places is {np.pi**3:.6e}') #Using the formatting to express pi in scientific notation

The cube of pi to 6 decimal places is 3.100628e+01


## 5.1 Structure of f-strings

# 6 Escape sequences

In [ ]:
print()

In [29]:
print('Line 1\n\tLine 2\n\t\tLine 3')

Line 1
	Line 2
		Line 3


In [16]:
print('You\'re 20 Years Old')

You're 20 Years Old


In [17]:
print('A\\B\\C')

A\B\C


In [18]:
print ('A\nB\nC')

A
B
C


In [19]:
print('A\tB\tC')

A	B	C


## 6.1 Self-documenting f-strings

In [20]:
x, y= 42, 24
print(f'{x=} and {y=}')

x=42 and y=24


In [21]:
x, y= 42/5, 24/5
print(f'{x=:.3f} and {y=:.6f}')

x=8.400 and y=4.800000


# 7 Computers read = from Right to Left!

In [30]:
x=40
y=x+2

In [31]:
y

42

In [32]:
y = 40
y = y + 2
print(y)

42


In [33]:
x=y=10

# 8 Shorter and Cleaner Code

In [22]:
y = 40
y = y + 2
y
y = 40
y += 2    # Same as y = y + 2
y


42

# 9 Python can be a prima-donna.

In [34]:
print(

_IncompleteInputError: incomplete input (149104261.py, line 1)

# 10 Best Practices for Scientific Computing

In [35]:
age = 10 # Student's age
student_age = 10

# 11 Looking for help

In [24]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



## References

## Footnotes