<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [8]:
py_list[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [10]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array//2
np_array [mask]

array([1, 2, 2, 3, 3, 4, 4, 5, 5, 6])

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array%3 == 0
np_array [mask]

array([3, 6, 9])

In [16]:
mask.sum()

np.int64(3)

In [11]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array//2 #quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [14]:
np_array%2 #remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [17]:
np_array[~mask]

array([ 1,  2,  4,  5,  7,  8, 10])

In [18]:
np_array[(np_array>3)&(np_array<8)] # '&' means 'and'

array([4, 5, 6, 7])

In [19]:
np.logical_and(np_array>3, np_array<3)

array([False, False, False, False, False, False, False, False, False,
       False])

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [22]:
py_list_2d[3][0]

4

In [23]:
np_array_2d[3,0] #Only for Numpy

np.str_('4')

In [29]:
np_array_2d[3:,1] # Only for Numpy

array(['D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

## 1.4 Growing lists

In [33]:
x=[1, 2] + [3]
print(x)
x+= [4]
print(x)
x+= [5]
print(x)
x+= [6]
print(x)
x+= [7]
print(x)
x+= [8]
print(x)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]


# Some loose ends

## 1.5 Tuples

In [34]:
a=(1, 2, 3)     # Define tuple

In [35]:
print(a[0])    # Access data

1


In [36]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [46]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [43]:
x=[1,2,3]
y=x.copy()
z=x.copy()

In [44]:
print(f'{x=}',f'{y=}',f'{z}')

x=[1, 2, 3] y=[1, 2, 3] [1, 2, 3]


In [45]:
x.append(1)
z.append(1000)
print(f'{x=}',f'{y=}',f'{z}')

x=[1, 2, 3, 1] y=[1, 2, 3] [1, 2, 3, 1000]


## Footnotes