<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [3]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

### Python List

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

### Numpy Arrays

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

### Dictionary

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [6]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

In [8]:
py_super_names[2]    # Forward indexing 

'Doctor Strange'

In [9]:
                     # We need to know the size 
                     # beforehand for this to work.
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [11]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [12]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [14]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

In [ ]:
py_list_2d = [[1, "A"], 
              [2, "B"], 
              [3, "C"], 
              [4, "D"],
              [5, "E"], 
              [6, "F"], 
              [7, "G"], 
              [8, "H"],
              [9, "I"], 
              [10, "J"]
              ]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [ ]:
np_array_2d #Both numbers and words are converted into strings 


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [21]:
py_list_2d #Only words are converted into strings

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## 2.1 Size

In [23]:
len(py_list_2d) #Checks the length of the list

10

In [26]:
len(np_array_2d)
np_array_2d.size #It has 20 elements, 10 rows x 2 columns

20

## 2.2 Arrays are fussy about type

In [28]:
py_list_2d = [[1, "A", 'b'], 
              [2, "B", 'c'], 
              [3, "C"], 
              [4, "D"],
              [5, "E"], 
              [6, "F"], 
              [7, "G"], 
              [8, "H"],
              [9, "I"], 
              [10, "J"]
              ]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
                                        # NumPy is very picky about the size and formatting of the arrays!!!

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

## 2.3 Adding a number

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

#### Lists

In [30]:
py_list

[1, 2, 3, 4, 5]

#### Arrays

In [33]:
np_array + 100

array([101, 102, 103, 104, 105])

## 2.4 Adding another list

In [36]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(np_array_1,np_array_2, sep='\n')

[1 2 3 4 5]
[10 20 30 40 50]


## 2.5 Multiplying by a Number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [38]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [39]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [41]:
py_list**2                      # Won't work for python lists!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [42]:
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

#### Arrays

In [43]:
np_array

array([1, 2, 3, 4, 5])

In [44]:
np_array == 3

array([False, False,  True, False, False])

In [45]:
np_array > 3

array([False, False, False,  True,  True])

In [ ]:
sum((np_array)>3) #Which is the same as doing sum([False, False, False,  True,  True])

np.int64(2)

In [51]:

sum([False, False, False,  True,  True])

2

In [54]:
mask = np_array < 3

np_array[mask]

array([1, 2])

In [53]:
py_list

[1, 2, 3, 4, 5]

## 2.8 Mathematics

In [55]:
max(py_list) 

5

#### Lists

In [56]:
min(py_list)

1

#### Arrays

In [57]:
np_array.mean()

np.float64(3.0)

In [59]:
np_array.sum()

np.int64(15)

In [60]:
np_array.std()

np.float64(1.4142135623730951)

In [61]:
sum(py_list)/len(py_list)

3.0

In [62]:
np_array.mean()

np.median(np_array)

np.float64(3.0)

## Footnotes